name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml

      - name: cvejson
        run: |
          # get latest cvejson script
          git clone https://github.com/cvebase/cvejson.git
          
          # generate updated cve.json into cvejson-data repo
          git clone https://github.com/cvebase/cvejson-data.git
          cd cvejson-data
          python ../cvejson/cvejson.py --cvebase-path ../cvebase.com
          
          # push updated cve.json to cvejson-data
          git add cve.json
          git commit -m "Update cve.json"
          git push "https://cve-ai:${{ secrets.GITHUB_TOKEN }}@github.com/cvebase/cvejson-data.git" HEAD:main --follow-tags
