name: Lint

on:
  push:
    branches: [ main ]
    paths:
    - 'cve/**'
    - 'researcher/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cvebase-wiki
          
      - name: Lint repo
        run: |
          cvebase-wiki lint -r $GITHUB_WORKSPACE
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "lint" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
